config/routes.rb
Rails.application.routes.draw do
  get '/' => "home#index", as: "main"
  post '/' => "home#index", as: "main_post"
  # post 'home/index'
  root 'home#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @company = params[:website]
    if @company.present?
      @company_url = @company.gsub("www.", "")
      @response = HTTParty.get("https://builtwith.com/#{@company_url}")
    end
    if @response.present?
      @dom = Nokogiri::HTML(@response.body)
      @tech = @dom.css('.techItem h3')[11]
      @cms = @tech.css('a')[1]
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<h1>MotionPoint BI_tool</h1>


<%= form_tag main_path do %>
<%= text_field_tag :website, nil, placeholder: "Enter a URL" %>
<%= submit_tag "search"%>
<% end %>

<!-- similar web stats -->
<h2>Company Stats</h2><br>
<p>Monthly Visits:</p>
<p>Bounce Rate:</p>
<p>Traffic By Countries: </p>
<p>Referring Sites:</p>
<p>Top Sources:</p>
<p>Organic Search:</p>
<p>Paid Search:</p>
<p>Sub-domains:</p>
<!-- Built With stats -->
<p>Framworks:</p>
<!-- Wappalyzer -->
<p>CMS: <%= @cms %> </p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MpBi1</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>